name: Run Reusable Dotnet Tests

on:
  push:
    branches:
      - main                  # roda apenas em push para main
  pull_request:
    branches:
      - main                  # roda em PRs para main
    types: [opened, synchronize, reopened]

jobs:
  call-dotnet-tests:
    permissions:
      contents: read
      actions: read
    uses: empreendimentopaguemenossa/github-standards-reusables/.github/workflows/dotnet-tests.yml@main
    with:
      dotnet-version: '9.0.x'
      configuration: 'Release'
    secrets: inherit
