name: Run Reusable Dotnet Tests

on:
  push:                       # dispara em push para qualquer branch
  pull_request:               # dispara em PRs de qualquer branch

jobs:
  call-dotnet-tests:
    uses: empreendimentopaguemenossa/github-standards-reusables/.github/workflows/dotnet-tests.yml@main
    with:
      branch: ${{ github.ref_name }}  # alteração de teste
