name: Run Reusable Dotnet Tests

on:
  push:                       # dispara em push para qualquer branch
  pull_request:               # dispara em PRs de qualquer branch

jobs:
  call-dotnet-tests:
    permissions:
      contents: read
    uses: empreendimentopaguemenossa/github-standards-reusables/.github/workflows/dotnet-tests.yml@main
    with:
      dotnet-version: '9.0.x'
      configuration: 'Release' #comentario teste
